### ISSUE TITLE
US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by bishalkc** [AjuntamentdeBarcelona/decidim-barcelona#195]
US-ASCII error 
```
Fetching https://github.com/AjuntamentdeBarcelona/decidim-barcelona
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:88:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:88:in `!~'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:88:in `say'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ui/shell.rb:105:in `tell_me'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ui/shell.rb:45:in `error'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:17:in `log_error'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:126:in `rescue in with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:104:in `load'
	from /usr/local/bundle/bin/bundle:104:in `<main>'
The command '/bin/sh -c bundle install --without development test' returned a non-zero code: 1
```

**Comment by oriolgual** [comment]
@bishalkc can you add more information about this?

**Comment by bishalkc** [comment]
I think problem lies here. 

in decidim-debabes/decidim-debates.gemspec
`  s.authors     = ["Josep Jaume Rey Peroy", "Marc Riera Casals", "Oriol Gual Oliva", "**Genís Matutes Pujol**"]`

adn in decidim-dataviz/decidim-dataviz.gemspec

`  s.authors     = ["David Morcillo **Muñoz**"]`

**Comment by oriolgual** [comment]
What command did you run to get this?

**Comment by bishalkc** [comment]
I ran bundle install and got that error.

**Comment by deivid-rodriguez** [comment]
I think this was fixed in bundler and the fix will be released in 1.16.2. See https://github.com/bundler/bundler/pull/6279.
