### ISSUE TITLE
Exception: Faraday::TimeoutError Decidim::Verifications::AuthorizationsController#create

### ISSUE THREAD

**Issue by Xfolchf** [AjuntamentdeBarcelona/decidim-barcelona#227]
**Describe the bug**
There was an exception on our error tracking. 
More information: https://sentry.io/share/issue/26db41e668d24d92bb23b1a0afe873c4/

**Expected behavior**
We shouldn't have exceptions nor errors 500 on production environment. 

**Stacktrace**
Net::ReadTimeout: Net::ReadTimeout
  app/services/census_authorization_handler.rb:83:in `response'
    response ||= Faraday.post Rails.application.secrets.census_url do |request|
  app/services/census_authorization_handler.rb:70:in `document_type_valid'
    return nil if response.blank?
...

**Extra data (please complete the following information):**
 - Device: Desktop 
 - Device OS: Windows 7
 - Browser: Chrome 67.0
 - Decidim Version: 0.12
 - Decidim installation: Decidim Barcelona

**Comment by iseimandi** [comment]
Hola, alguién ha podido solucionnar este error? estoy teniendo error 500 al agregar auterizaciones. Los pasos realizados son:
Agrego en el archivo -> config/initializers/decidim.rb
      Decidim::Verifications.register_workflow(:census_authorization_handler) do |auth|
         auth.form = "CensusAuthorizationHandler"
      end
Así obtengo la habilitación de la autorización desde la Administración.

Luego agrego el formulario en app/views/census_authorization/_form.html.erb 

Y por último -> app/services/census_authorization_handler.rb 
El error que obtengo al hacer Enviar en el formulario -> es error 500 , el log de errores no dá ninguna pista del motivo del error.
Independientemente de lo que escriba en el archivo census_authorization_handler.rb, obtengo siempre el mismo error.

Versión Decidim: 0.22

Si pueden ayudarme con alguna idea de cuál podría ser el problema, lo agradeceré muchisimo!!

**Comment by iseimandi** [comment]
Hi, has someone had the following error -> 500 error while adding auctions. The steps performed are:
I add in the file -> config / initializers / decidim.rb
      Decidim :: Verifications.register_workflow (: census_authorization_handler) do | auth |
         auth.form = "CensusAuthorizationHandler"
      end
Thus I obtain the authorization of the authorization from the Administration.

Then I add the form in app / views / census_authorization / _form.html.erb

And finally -> app / services / census_authorization_handler.rb
The error I get when doing Submit on the form -> is error 500, the error log does not give any clue of the reason for the error.
Regardless of what I write to the census_authorization_handler.rb file, I always get the same error.

Decidim Version: 0.22

If you can help me with any ideas of what the problem might be, I will greatly appreciate it !!
